export const STATE_DISTRICTS: Record<string, string[]> = {
  kul: ["Kuala Lumpur"],
  sgr: [
    "Shah Alam",
    "Petaling Jaya",
    "Subang Jaya",
    "Klang",
    "Ampang Jaya",
    "Cheras",
    "Kajang",
    "Rawang",
    "Sepang",
    "Sabak Bernam",
    "Kuala Selangor",
    "Kuala Langat",
    "Hulu Langat",
    "Hulu Selangor",
    "Gombak",
  ],
  jhr: [
    "Johor Bahru",
    "Iskandar Puteri",
    "Pasir Gudang",
    "Batu Pahat",
    "Muar",
    "Kluang",
    "Kota Tinggi",
    "Mersing",
    "Segamat",
    "Tangkak",
    "Pontian",
    "Kulai",
  ],
  pns: [
    "George Town",
    "Butterworth",
    "Bukit Mertajam",
    "Nibong Tebal",
    "Kepala Batas",
    "Balik Pulau",
  ],
  pgk: [
    "Ipoh",
    "Taiping",
    "Kampar",
    "Teluk Intan",
    "Lumut",
    "Batu Gajah",
    "Parit Buntar",
    "Tapah",
  ],
  kdh: [
    "Alor Setar",
    "Sungai Petani",
    "Kulim",
    "Bandar Baharu",
    "Langkawi",
    "Pendang",
    "Sik",
    "Baling",
    "Padang Terap",
    "Kota Setar",
    "Pokok Sena",
  ],
  ktn: [
    "Kota Bharu",
    "Pasir Mas",
    "Tumpat",
    "Pasir Puteh",
    "Bachok",
    "Machang",
    "Kuala Krai",
    "Gua Musang",
    "Jeli",
    "Tanah Merah",
  ],
  trg: [
    "Kuala Terengganu",
    "Kemaman",
    "Dungun",
    "Marang",
    "Hulu Terengganu",
    "Besut",
    "Setiu",
  ],
  phg: [
    "Kuantan",
    "Temerloh",
    "Jerantut",
    "Maran",
    "Raub",
    "Bentong",
    "Lipis",
    "Cameron Highlands",
    "Pekan",
    "Rompin",
    "Bera",
  ],
  nsm: [
    "Seremban",
    "Port Dickson",
    "Nilai",
    "Tampin",
    "Jempol",
    "Kuala Pilah",
    "Rembau",
    "Jelebu",
  ],
  mlk: [
    "Melaka",
    "Alor Gajah",
    "Jasin",
  ],
  swk: [
    "Kuching",
    "Sibu",
    "Miri",
    "Bintulu",
    "Sri Aman",
    "Sarikei",
    "Kapit",
    "Limbang",
    "Lawas",
    "Betong",
    "Mukah",
    "Dalat",
    "Matang",
    "Samarahan",
    "Serian",
    "Bau",
    "Lundu",
  ],
  sbh: [
    "Kota Kinabalu",
    "Sandakan",
    "Tawau",
    "Lahad Datu",
    "Keningau",
    "Beaufort",
    "Semporna",
    "Kudat",
    "Ranau",
    "Kota Belud",
    "Kota Marudu",
    "Pitas",
    "Tuaran",
    "Papar",
    "Penampang",
    "Putatan",
  ],
  prl: [
    "Kangar",
    "Arau",
    "Padang Besar",
  ],
  lby: ["Labuan"],
  pjy: ["Putrajaya", "Cyberjaya"],
};

export function getDistrictsForState(stateCode: string): string[] {
  return STATE_DISTRICTS[stateCode] || [];
}

export function getAllCities(): string[] {
  const all = new Set<string>();
  Object.values(STATE_DISTRICTS).forEach((districts) => {
    districts.forEach((d) => all.add(d));
  });
  return Array.from(all).sort();
}